import EStyleSheet from 'react-native-extended-stylesheet';
import {StyleSheet} from 'react-native';

const styles = EStyleSheet.create({
  item: {
    flex: 1,
    margin: 18,
    borderRadius: 2,
    backgroundColor: '$white',
    shadowColor: 'rgba(0, 0, 0, 0.06)',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowRadius: 13,
    shadowOpacity: 1,
  },
  top: {
    flex: 1,
    flexDirection: 'row',
  },
  topLeft: {
    marginTop: 15,
    marginLeft: 15,
    flexDirection: 'column',
    justifyContent: 'flex-start',
  },
  topRight: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  amountTitle: {
    fontSize: 12,
    fontWeight: '900',
    fontStyle: 'normal',
    letterSpacing: -0.34,
    color: '$black',
  },
  amount: {
    fontSize: 32,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.91,
    color: '$black',
    marginVertical: 5,
  },
  date: {
    marginTop: 15,
    marginRight: 15,
    fontSize: 12,
    fontWeight: '900',
    fontStyle: 'normal',
    letterSpacing: -0.34,
    color: '$brownGrey',
  },
  separator: {
    backgroundColor: '$veryLightPink',
    height: StyleSheet.hairlineWidth,
    // flex: 1,
    marginTop: 10,
    marginHorizontal: 15,
  },
  nameRow: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    justifyContent: 'center',
  },
  name: {
    marginTop: 15,
    marginLeft: 15,
    fontSize: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: '$greyishBrown',
  },
  merchant: {
    marginTop: 15,
    marginLeft: 5,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginVertical: 5,
    borderRadius: 2,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: '900',
    fontStyle: 'normal',
    letterSpacing: -0.43,
    color: '$greyishBrown',
  },
  receiptRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignSelf: 'flex-start',
    justifyContent: 'center',
    marginLeft: 15,
  },
  receiptCount: {
    marginLeft: 10,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: '$greyishBrown',
    textDecorationLine: 'underline',
  },
  commentRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignSelf: 'flex-start',
    justifyContent: 'center',
    marginLeft: 15,
  },
  comment: {
    marginLeft: 10,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: '$brownGreyTwo',
  },
  buttons: {
    marginTop: 20,
    borderTopColor: '$veryLightPink',
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
  },
  button: {
    flex: 1,
    marginTop: 15,
    marginBottom: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    fontSize: 12,
    fontWeight: '500',
    fontStyle: 'normal',
    letterSpacing: -0.3,
    color: '$black',
  },
  buttonSeparator: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: '$veryLightPink',
  },
});

export default styles;
